### ISSUE TITLE
As a [__type of user__], I want to be able to find the information I need on the dashboard

### ISSUE THREAD

**Issue by CamKirk** [moneytrees/moneybags#13]
So that I can see how I am doing at a quick glance

**Comment by CamKirk** [comment]
Please begin prototyping the charts immediately, so we can get information on what direction to go.

**Comment by mcougill** [comment]
hey! I'm starting a user experience flow chart on draw.io. This will help us outline what the user needs to see and when as they're progressing through our app. I haven't added anything to the flow chart yet, but want to make sure y'all are able to access it: https://www.draw.io/#G13f0vD84DMFhJnwfGL_7yKv5A-hhF4n_y can you edit on your end? You should be able to but I've never shared a chart on here so just wanna double check

**Comment by mcougill** [comment]
My focus tonight after work is to start building the chart out - as a reference, here's an article overviewing what sort of chart we're aiming for: https://www.startuprocket.com/articles/how-to-create-a-user-experience-flow-chart-ux-flow-chart

**Comment by chrisjones0517** [comment]
I have the basic javascript code and react-vis in place for the pie graph and parsing of the data that is returned from the '/transactions' route. I'm working on the line graph now with linear regression.

**Comment by mcougill** [comment]
cool! to confirm - pie graph is showing spend category and linear regression is showing projected savings?
