### ISSUE TITLE
Code Registration Page

### ISSUE THREAD

**Issue by wabernathy96** [moneytrees/moneybags#20]

**Comment by CamKirk** [comment]
Should we close this and move to the USER team?

**Comment by wabernathy96** [comment]
Yes, its done on the back-end just need a scrum master to push up to develop

**Comment by CamKirk** [comment]
@nhoben let's assign this to someone on front-end?

**Comment by wabernathy96** [comment]
Register API && view routes online @ /api/users/register and /register
