### ISSUE TITLE
Integrate ItemCreator (Plaid LINK) component with User transactions/model

### ISSUE THREAD

**Issue by thaiscmky** [moneytrees/moneybags#68]
Relates to #15

* Make sure public_key is saved to the user's account if the logged in user does not have a public key
* Make sure to NOT make a request for a public_key if the user signed in currently has a public token
* Make sure to save the access_key and item_id for the user's institution connected institution
* Make sure to save the (same) access_key and each user account item_id
* Make sure the plaid controller's public_key, access_key, and item_id for each appropriate request is being passed from the database if those values do exist in the database

**Comment by sernikitin** [comment]
done
